modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/city-craft/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="citycraft:asphalt_with_white_broken_middle_line"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/CityCraft.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/city-craft"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod expands the game with vanilla friendly streets, signs and other decoration blocks to transform your world into a huge city!'''


[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

