package xxrexraptorxx.citycraft.datagen;

import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.RegistryObject;
import xxrexraptorxx.citycraft.registry.ModBlocks;

import java.util.Set;

public class BlockLootTables extends BlockLootSubProvider {

    public BlockLootTables() {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags());
    }

    @Override
    protected void generate() {

        this.dropSelf(ModBlocks.ASPHALT_BLOCK.get());
        this.dropSelf(ModBlocks.CRACKED_ASPHALT.get());
        this.dropSelf(ModBlocks.POTHOLE_ASPHALT.get());
        this.dropSelf(ModBlocks.MOSSY_ASPHALT.get());
        this.dropSelf(ModBlocks.DIRTY_ASPHALT.get());

        this.dropSelf(ModBlocks.WHITE_ASPHALT.get());
        this.dropSelf(ModBlocks.ORANGE_ASPHALT.get());
        this.dropSelf(ModBlocks.MAGENTA_ASPHALT.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_ASPHALT.get());
        this.dropSelf(ModBlocks.YELLOW_ASPHALT.get());
        this.dropSelf(ModBlocks.LIME_ASPHALT.get());
        this.dropSelf(ModBlocks.RED_ASPHALT.get());
        this.dropSelf(ModBlocks.PINK_ASPHALT.get());
        this.dropSelf(ModBlocks.GRAY_ASPHALT.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_ASPHALT.get());
        this.dropSelf(ModBlocks.CYAN_ASPHALT.get());
        this.dropSelf(ModBlocks.PURPLE_ASPHALT.get());
        this.dropSelf(ModBlocks.BLUE_ASPHALT.get());
        this.dropSelf(ModBlocks.BROWN_ASPHALT.get());
        this.dropSelf(ModBlocks.GREEN_ASPHALT.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_HATCHING.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_SIDE_DOTS.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DOUBLE_SIDE_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_HATCHING.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_HATCHING.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_DOTS.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DOUBLE_SIDE_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_HATCHING.get());

        this.add(ModBlocks.ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_SLAB.get()));
        this.add(ModBlocks.CRACKED_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.CRACKED_ASPHALT_SLAB.get()));
        this.add(ModBlocks.POTHOLE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.POTHOLE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.MOSSY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.MOSSY_ASPHALT_SLAB.get()));
        this.add(ModBlocks.DIRTY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.DIRTY_ASPHALT_SLAB.get()));

        this.add(ModBlocks.WHITE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.WHITE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.ORANGE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.ORANGE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.MAGENTA_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.MAGENTA_ASPHALT_SLAB.get()));
        this.add(ModBlocks.LIGHT_BLUE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.LIGHT_BLUE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.YELLOW_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.YELLOW_ASPHALT_SLAB.get()));
        this.add(ModBlocks.LIME_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.LIME_ASPHALT_SLAB.get()));
        this.add(ModBlocks.RED_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.RED_ASPHALT_SLAB.get()));
        this.add(ModBlocks.PINK_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.PINK_ASPHALT_SLAB.get()));
        this.add(ModBlocks.GRAY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.GRAY_ASPHALT_SLAB.get()));
        this.add(ModBlocks.LIGHT_GRAY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.LIGHT_GRAY_ASPHALT_SLAB.get()));
        this.add(ModBlocks.CYAN_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.CYAN_ASPHALT_SLAB.get()));
        this.add(ModBlocks.PURPLE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.PURPLE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.BLUE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.BLUE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.BROWN_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.BROWN_ASPHALT_SLAB.get()));
        this.add(ModBlocks.GREEN_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.GREEN_ASPHALT_SLAB.get()));

        this.add(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_HATCHING_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_SIDE_DOTS_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_SIDE_DOTS_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DOUBLE_SIDE_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DOUBLE_SIDE_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_HATCHING_SLAB.get()));

        this.add(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_HATCHING_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_DOTS_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_DOTS_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DOUBLE_SIDE_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DOUBLE_SIDE_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_HATCHING_SLAB.get()));

        this.dropSelf(ModBlocks.BOOST_ASPHALT.get());
        this.add(ModBlocks.BOOST_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.BOOST_ASPHALT_SLAB.get()));
        this.add(ModBlocks.YELLOW_BUMPER_SLAB.get(), block -> createSlabItemTable(ModBlocks.YELLOW_BUMPER_SLAB.get()));
        this.add(ModBlocks.RED_BUMPER_SLAB.get(), block -> createSlabItemTable(ModBlocks.RED_BUMPER_SLAB.get()));

        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_A.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_B.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_C.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_D.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_E.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_F.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_G.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_H.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_I.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_J.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_K.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_L.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_M.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_N.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_O.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_P.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_Q.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_R.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_S.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_T.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_U.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_V.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_W.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_X.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_Y.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_Z.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_A.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_B.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_C.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_D.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_E.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_F.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_G.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_H.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_I.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_J.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_K.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_L.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_M.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_N.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_O.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_P.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_Q.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_R.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_S.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_T.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_U.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_V.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_W.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_X.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_Y.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_Z.get());

        this.add(ModBlocks.ASPHALT_WITH_WHITE_A_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_A_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_B_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_B_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_C_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_C_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_D_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_D_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_E_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_E_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_F_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_F_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_G_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_G_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_H_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_H_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_I_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_I_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_J_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_J_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_K_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_K_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_L_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_L_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_M_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_M_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_N_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_N_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_O_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_O_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_P_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_P_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_Q_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_Q_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_R_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_R_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_S_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_S_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_T_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_T_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_U_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_U_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_V_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_V_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_W_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_W_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_X_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_X_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_Y_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_Y_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_Z_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_Z_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_A_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_A_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_B_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_B_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_C_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_C_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_D_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_D_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_E_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_E_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_F_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_F_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_G_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_G_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_H_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_H_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_I_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_I_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_J_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_J_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_K_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_K_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_L_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_L_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_M_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_M_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_N_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_N_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_O_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_O_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_P_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_P_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_Q_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_Q_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_R_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_R_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_S_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_S_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_T_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_T_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_U_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_U_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_V_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_V_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_W_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_W_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_X_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_X_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_Y_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_Y_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_Z_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_Z_SLAB.get()));

        this.dropSelf(ModBlocks.IRON_POLE.get());
        this.dropSelf(ModBlocks.YELLOW_POLE.get());
        this.dropSelf(ModBlocks.BLACK_POLE.get());
        this.dropSelf(ModBlocks.WHITE_POLE.get());
        this.dropSelf(ModBlocks.RED_WHITE_POLE.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_POLE.get());
        this.dropSelf(ModBlocks.RED_POLE.get());

        this.dropSelf(ModBlocks.STONE_POST.get());
        this.dropSelf(ModBlocks.YELLOW_POST.get());
        this.dropSelf(ModBlocks.BLACK_POST.get());
        this.dropSelf(ModBlocks.WHITE_POST.get());
        this.dropSelf(ModBlocks.RED_WHITE_POST.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_POST.get());
        this.dropSelf(ModBlocks.RED_POST.get());
        this.dropSelf(ModBlocks.ROAD_EDGE_POST.get());
        this.dropSelf(ModBlocks.ORANGE_ROAD_EDGE_POST.get());

        this.dropSelf(ModBlocks.YELLOW_CHAIN.get());
        this.dropSelf(ModBlocks.BLACK_CHAIN.get());
        this.dropSelf(ModBlocks.WHITE_CHAIN.get());
        this.dropSelf(ModBlocks.RED_CHAIN.get());

        this.dropSelf(ModBlocks.LEFT_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.CAMPING_EU_SIGN.get());
        this.dropSelf(ModBlocks.PR_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_ROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_NARROWING_EU_SIGN.get());
        this.dropSelf(ModBlocks.CHURCH_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PARKING_EU_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_EU_SIGN.get());
        this.dropSelf(ModBlocks.NARROWING_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_CARS_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCK_PASSING_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.ONGOING_TRAFFIC_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.END_ALL_LIMITS_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIRECTION_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PASSING_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.CATTLE_EU_SIGN.get());
        this.dropSelf(ModBlocks.CAFE_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_VEHICLES_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCKS_EU_SIGN.get());
        this.dropSelf(ModBlocks.BUS_EU_SIGN.get());
        this.dropSelf(ModBlocks.DANGER_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_ENTER_EU_SIGN.get());
        this.dropSelf(ModBlocks.INTERSECTION_EU_SIGN.get());
        this.dropSelf(ModBlocks.EIGHTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.ASCEND_EU_SIGN.get());
        this.dropSelf(ModBlocks.CYCLES_EU_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_BAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PEDESTRIANS_EU_SIGN.get());
        this.dropSelf(ModBlocks.PASS_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.DESCEND_EU_SIGN.get());
        this.dropSelf(ModBlocks.FIRST_AID_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_BICYCLES_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_OVER_ONCOMING_TRAFFIC_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_THROUGH_ROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.CREEPER_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_ROAD_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DOUBLE_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_PATH_EU_SIGN.get());
        this.dropSelf(ModBlocks.JAMS_EU_SIGN.get());
        this.dropSelf(ModBlocks.KM_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PASSING_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCK_PASSING_EU_SIGN.get());
        this.dropSelf(ModBlocks.END_LINE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PASS_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PARKING_ALONG_CARRIAGEWAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.SIXTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIANS_EU_SIGN.get());
        this.dropSelf(ModBlocks.CALMING_AREA_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_TURN_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.ONCOMING_TRAFFIC_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_HERE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.ONE_WAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.BUS_STOP_EU_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIAN_CROSSING_EU_SIGN.get());
        this.dropSelf(ModBlocks.INFO_EU_SIGN.get());
        this.dropSelf(ModBlocks.DISABLED_EU_SIGN.get());
        this.dropSelf(ModBlocks.TEN_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.CROSSBUCK_EU_SIGN.get());
        this.dropSelf(ModBlocks.THIRTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.HOTEL_EU_SIGN.get());
        this.dropSelf(ModBlocks.GATE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PETROL_STATION_EU_SIGN.get());
        this.dropSelf(ModBlocks.CHILDREN_EU_SIGN.get());
        this.dropSelf(ModBlocks.CROSSWALK_EU_SIGN.get());
        this.dropSelf(ModBlocks.END_CALMING_AREA_EU_SIGN.get());
        this.dropSelf(ModBlocks.GUIDE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_GARAGE_EU_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.HUNDRED_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_U_TURN_EU_SIGN.get());
        this.dropSelf(ModBlocks.HUNDRED_TWENTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.RAILROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.REPAIR_EU_SIGN.get());
        this.dropSelf(ModBlocks.RESTAURANT_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIRECTION_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DOUBLE_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_HERE_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_NARROWING_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.ROADWORKS_EU_SIGN.get());
        this.dropSelf(ModBlocks.ROCKFALL_EU_SIGN.get());
        this.dropSelf(ModBlocks.ROUNDABOUT_EU_SIGN.get());
        this.dropSelf(ModBlocks.SIDEWALK_EU_SIGN.get());
        this.dropSelf(ModBlocks.SIGNAL_EU_SIGN.get());
        this.dropSelf(ModBlocks.SLIPPERINESS_EU_SIGN.get());
        this.dropSelf(ModBlocks.SNOW_EU_SIGN.get());
        this.dropSelf(ModBlocks.STOP_EU_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.TAXI_EU_SIGN.get());
        this.dropSelf(ModBlocks.TELEPHONE_EU_SIGN.get());
        this.dropSelf(ModBlocks.UNEVEN_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARN_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_ALT_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.WC_EU_SIGN.get());
        this.dropSelf(ModBlocks.WEIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.WET_EU_SIGN.get());
        this.dropSelf(ModBlocks.YIELD_RIGHT_OF_WAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.NATURE_RESERVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.MOTORWAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.MOTORWAY_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.WATER_PROTECTION_AREA_EU_SIGN.get());

        this.dropSelf(ModBlocks.REPAIR_US_SIGN.get());
        this.dropSelf(ModBlocks.HILL_US_SIGN.get());
        this.dropSelf(ModBlocks.GUIDE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ADDED_LINE_US_SIGN.get());
        this.dropSelf(ModBlocks.INFO_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ENTERING_ROADWAY_MERGE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.DOUBLE_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.HOTEL_US_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIANS_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_BICYCLE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_LANE_ENDS_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIAGONAL_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.HANDICAPPED_ACCESSIBLE_US_SIGN.get());
        this.dropSelf(ModBlocks.RESTAURANT_US_SIGN.get());
        this.dropSelf(ModBlocks.HAIRPIN_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.AIRPORT_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIRECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.RAILROAD_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ENTERING_ROADWAY_MERGE_US_SIGN.get());
        this.dropSelf(ModBlocks.DRINKING_WATER_US_SIGN.get());
        this.dropSelf(ModBlocks.CRAFT_CITY_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_LEFT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIAGONAL_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.BATHROOMS_US_SIGN.get());
        this.dropSelf(ModBlocks.LITTER_BARREL_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCKS_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_TURN_ONLY_US_SIGN.get());
        this.dropSelf(ModBlocks.FORTYFIVE_ADVISORY_SPEED_US_SIGN.get());
        this.dropSelf(ModBlocks.LIGHT_RAIL_TRANSIT_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.CRAFT_CITY_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.HOSPITAL_US_SIGN.get());
        this.dropSelf(ModBlocks.GAS_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.CATTLE_US_SIGN.get());
        this.dropSelf(ModBlocks.HANDICAPED_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.PICNIC_AREA_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_U_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIAGONAL_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ADDED_LINE_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_LANE_ENDS_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_SIDE_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.PLAYGROUND_AHEAD_US_SIGN.get());
        this.dropSelf(ModBlocks.DIESEL_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.THIRTYFIVE_ADVISORY_SPEED_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIAGONAL_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.CREEPER_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIAGONAL_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.LOUNDRY_FACILITY_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_PARKING_US_SIGN.get());
        this.dropSelf(ModBlocks.TWENTYFIVE_ADVISORY_SPEED_US_SIGN.get());
        this.dropSelf(ModBlocks.DOUBLE_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.CAMPING_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.CIRCULAR_INTERSECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_MERGING_TRAFFIC_US_SIGN.get());
        this.dropSelf(ModBlocks.DIVIDED_HIGHWAY_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_PEDESTRIANS_US_SIGN.get());
        this.dropSelf(ModBlocks.CROSSBUCK_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.ELECTRIC_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_REVERSE_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.MEDICAL_SERVICE_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIRECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_RIGHT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.CROSS_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.DOUBLE_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIAGONAL_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_MERGING_TRAFFIC_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_REVERSE_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_SIDE_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_ONLY_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.ROAD_NARROWS_US_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_ANGLE_LEFT_US_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_ANGLE_RIGHT_US_SIGN.get());
        this.dropSelf(ModBlocks.SIGNAL_US_SIGN.get());
        this.dropSelf(ModBlocks.SLIPPERY_US_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_AHEAD_ONLY_US_SIGN.get());
        this.dropSelf(ModBlocks.SWIMMING_AREA_US_SIGN.get());
        this.dropSelf(ModBlocks.T_INTERSECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.TELEPHONE_US_SIGN.get());
        this.dropSelf(ModBlocks.TRUCK_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.TRUCK_ROLLOVER_WARNING_US_SIGN.get());
        this.dropSelf(ModBlocks.TWO_WAY_TRAFFIC_US_SIGN.get());
        this.dropSelf(ModBlocks.VERY_SHARP_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.WINTER_RECREATION_AREA_US_SIGN.get());
        this.dropSelf(ModBlocks.WINDING_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.WORKERS_US_SIGN.get());
        this.dropSelf(ModBlocks.Y_INTERSECTION_US_SIGN.get());

        this.dropSelf(ModBlocks.ROUND_SIGN.get());
        this.dropSelf(ModBlocks.TRIANGLE_SIGN.get());
        this.dropSelf(ModBlocks.RECTANGLE_SIGN.get());
        this.dropSelf(ModBlocks.SQUARE_SIGN.get());
        this.dropSelf(ModBlocks.CROSS_SIGN.get());
        this.dropSelf(ModBlocks.UPSIDE_DOWN_TRIANGLE_SIGN.get());
        this.dropSelf(ModBlocks.RHOMBUS_SIGN.get());
        this.dropSelf(ModBlocks.OCTAGON_SIGN.get());
        this.dropSelf(ModBlocks.BAKE_SIGN.get());

        this.add(ModBlocks.DRAIN_COVER.get(), block -> createSlabItemTable(ModBlocks.DRAIN_COVER.get()));
        this.add(ModBlocks.DRAIN_COVER_GRID.get(), block -> createSlabItemTable(ModBlocks.DRAIN_COVER_GRID.get()));

        this.dropSelf(ModBlocks.IRON_FENCE.get());
        this.dropSelf(ModBlocks.TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.RED_WHITE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.DOUBLE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.DOUBLE_YELLOW_BLACK_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.DOUBLE_RED_WHITE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.RED_WHITE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_TRAFFIC_BARRIER.get());

        this.dropSelf(ModBlocks.BLACK_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.WHITE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.ORANGE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.MAGENTA_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.YELLOW_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.LIME_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.PINK_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.GRAY_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.CYAN_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.PURPLE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.BLUE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.BROWN_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.GREEN_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.RED_CONCRETE_WALL.get());

        this.dropSelf(ModBlocks.BLOCK_PAINTER.get());
    }


    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries().stream().map(RegistryObject::get)::iterator;
    }

}
