package xxrexraptorxx.citycraft.datagen;

import java.util.Set;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import xxrexraptorxx.citycraft.registry.ModBlocks;

public class BlockLootTables extends BlockLootSubProvider {

    public BlockLootTables(HolderLookup.Provider lookupProvider) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), lookupProvider);
    }


    @Override
    protected void generate() {

        this.dropSelf(ModBlocks.ASPHALT_BLOCK.get());
        this.dropSelf(ModBlocks.CRACKED_ASPHALT.get());
        this.dropSelf(ModBlocks.POTHOLE_ASPHALT.get());
        this.dropSelf(ModBlocks.MOSSY_ASPHALT.get());
        this.dropSelf(ModBlocks.DIRTY_ASPHALT.get());

        this.dropSelf(ModBlocks.WHITE_ASPHALT.get());
        this.dropSelf(ModBlocks.ORANGE_ASPHALT.get());
        this.dropSelf(ModBlocks.MAGENTA_ASPHALT.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_ASPHALT.get());
        this.dropSelf(ModBlocks.YELLOW_ASPHALT.get());
        this.dropSelf(ModBlocks.LIME_ASPHALT.get());
        this.dropSelf(ModBlocks.RED_ASPHALT.get());
        this.dropSelf(ModBlocks.PINK_ASPHALT.get());
        this.dropSelf(ModBlocks.GRAY_ASPHALT.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_ASPHALT.get());
        this.dropSelf(ModBlocks.CYAN_ASPHALT.get());
        this.dropSelf(ModBlocks.PURPLE_ASPHALT.get());
        this.dropSelf(ModBlocks.BLUE_ASPHALT.get());
        this.dropSelf(ModBlocks.BROWN_ASPHALT.get());
        this.dropSelf(ModBlocks.GREEN_ASPHALT.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_HATCHING.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_SIDE_DOTS.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DOUBLE_SIDE_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_HATCHING.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_HATCHING.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_DOTS.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SIDE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DOUBLE_SIDE_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SOLID_AND_BROKEN_MIDDLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_DOUBLE_LINE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_FRAME.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_HATCHING.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_RIGHT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_RIGHT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_RIGHT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_RIGHT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_RIGHT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_RIGHT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_RIGHT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LEFT_EDGE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_RIGHT_EDGE.get());

        this.add(ModBlocks.ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_SLAB.get()));
        this.add(ModBlocks.CRACKED_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.CRACKED_ASPHALT_SLAB.get()));
        this.add(ModBlocks.POTHOLE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.POTHOLE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.MOSSY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.MOSSY_ASPHALT_SLAB.get()));
        this.add(ModBlocks.DIRTY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.DIRTY_ASPHALT_SLAB.get()));

        this.add(ModBlocks.WHITE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.WHITE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.ORANGE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.ORANGE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.MAGENTA_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.MAGENTA_ASPHALT_SLAB.get()));
        this.add(ModBlocks.LIGHT_BLUE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.LIGHT_BLUE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.YELLOW_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.YELLOW_ASPHALT_SLAB.get()));
        this.add(ModBlocks.LIME_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.LIME_ASPHALT_SLAB.get()));
        this.add(ModBlocks.RED_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.RED_ASPHALT_SLAB.get()));
        this.add(ModBlocks.PINK_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.PINK_ASPHALT_SLAB.get()));
        this.add(ModBlocks.GRAY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.GRAY_ASPHALT_SLAB.get()));
        this.add(ModBlocks.LIGHT_GRAY_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.LIGHT_GRAY_ASPHALT_SLAB.get()));
        this.add(ModBlocks.CYAN_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.CYAN_ASPHALT_SLAB.get()));
        this.add(ModBlocks.PURPLE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.PURPLE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.BLUE_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.BLUE_ASPHALT_SLAB.get()));
        this.add(ModBlocks.BROWN_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.BROWN_ASPHALT_SLAB.get()));
        this.add(ModBlocks.GREEN_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.GREEN_ASPHALT_SLAB.get()));

        this.add(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_HATCHING_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_SIDE_DOTS_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_SIDE_DOTS_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_STRAIGHT_AND_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DOUBLE_SIDE_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DOUBLE_SIDE_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_DIAGONAL_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_HATCHING_SLAB.get()));

        this.add(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_DOUBLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_HATCHING_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_DOTS_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_SIDE_DOTS_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SIDE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SIDE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_RIGHT_ARROW_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_STRAIGHT_AND_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DOUBLE_SIDE_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DOUBLE_SIDE_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_MIDDLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_SOLID_AND_BROKEN_MIDDLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_DIAGONAL_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_BROKEN_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_LINE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_DIAGONAL_DOUBLE_LINE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_FRAME_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_FRAME_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_HATCHING_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_HATCHING_SLAB.get()));

        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LEFT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_RIGHT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_RIGHT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LEFT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_RIGHT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_THICK_MIDDLE_RIGHT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LEFT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_RIGHT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_RIGHT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get(),
                block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_DOUBLE_RIGHT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LEFT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_LEFT_EDGE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_RIGHT_EDGE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_THICK_MIDDLE_RIGHT_EDGE_SLAB.get()));

        this.dropSelf(ModBlocks.BOOST_ASPHALT.get());
        this.add(ModBlocks.BOOST_ASPHALT_SLAB.get(), block -> createSlabItemTable(ModBlocks.BOOST_ASPHALT_SLAB.get()));
        this.add(ModBlocks.YELLOW_BUMPER_SLAB.get(), block -> createSlabItemTable(ModBlocks.YELLOW_BUMPER_SLAB.get()));
        this.add(ModBlocks.RED_BUMPER_SLAB.get(), block -> createSlabItemTable(ModBlocks.RED_BUMPER_SLAB.get()));

        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_A.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_B.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_C.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_D.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_E.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_F.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_G.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_H.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_I.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_J.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_K.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_L.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_M.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_N.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_O.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_P.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_Q.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_R.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_S.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_T.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_U.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_V.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_W.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_X.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_Y.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_Z.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_A.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_B.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_C.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_D.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_E.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_F.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_G.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_H.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_I.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_J.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_K.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_L.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_M.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_N.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_O.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_P.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_Q.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_R.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_S.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_T.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_U.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_V.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_W.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_X.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_Y.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_Z.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_0.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_1.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_2.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_3.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_4.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_5.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_6.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_7.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_8.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_9.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_COMMA.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DASH.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DOT.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_EXCLAMATION.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_QUESTION.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_SLASH.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_0.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_1.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_2.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_3.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_4.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_5.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_6.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_7.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_8.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_9.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_COMMA.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DASH.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DOT.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_EXCLAMATION.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_QUESTION.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_SLASH.get());

        this.add(ModBlocks.ASPHALT_WITH_WHITE_A_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_A_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_B_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_B_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_C_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_C_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_D_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_D_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_E_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_E_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_F_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_F_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_G_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_G_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_H_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_H_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_I_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_I_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_J_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_J_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_K_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_K_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_L_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_L_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_M_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_M_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_N_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_N_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_O_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_O_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_P_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_P_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_Q_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_Q_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_R_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_R_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_S_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_S_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_T_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_T_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_U_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_U_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_V_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_V_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_W_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_W_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_X_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_X_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_Y_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_Y_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_Z_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_Z_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_A_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_A_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_B_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_B_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_C_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_C_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_D_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_D_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_E_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_E_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_F_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_F_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_G_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_G_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_H_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_H_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_I_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_I_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_J_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_J_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_K_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_K_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_L_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_L_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_M_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_M_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_N_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_N_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_O_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_O_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_P_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_P_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_Q_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_Q_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_R_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_R_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_S_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_S_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_T_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_T_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_U_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_U_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_V_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_V_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_W_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_W_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_X_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_X_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_Y_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_Y_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_Z_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_Z_SLAB.get()));

        this.add(ModBlocks.ASPHALT_WITH_WHITE_0_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_0_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_1_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_1_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_2_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_2_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_3_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_3_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_4_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_4_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_5_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_5_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_6_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_6_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_7_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_7_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_8_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_8_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_9_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_9_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_COMMA_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_COMMA_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DASH_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DASH_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DOT_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DOT_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_EXCLAMATION_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_EXCLAMATION_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_QUESTION_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_QUESTION_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_SLASH_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_SLASH_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_0_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_0_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_1_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_1_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_2_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_2_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_3_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_3_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_4_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_4_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_5_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_5_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_6_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_6_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_7_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_7_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_8_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_8_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_9_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_9_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_COMMA_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_COMMA_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DASH_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DASH_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DOT_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DOT_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_EXCLAMATION_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_EXCLAMATION_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_QUESTION_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_QUESTION_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_SLASH_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_SLASH_SLAB.get()));

        this.dropSelf(ModBlocks.IRON_POLE.get());
        this.dropSelf(ModBlocks.YELLOW_POLE.get());
        this.dropSelf(ModBlocks.BLACK_POLE.get());
        this.dropSelf(ModBlocks.WHITE_POLE.get());
        this.dropSelf(ModBlocks.RED_WHITE_POLE.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_POLE.get());
        this.dropSelf(ModBlocks.RED_POLE.get());

        this.dropSelf(ModBlocks.STONE_POST.get());
        this.dropSelf(ModBlocks.YELLOW_POST.get());
        this.dropSelf(ModBlocks.BLACK_POST.get());
        this.dropSelf(ModBlocks.WHITE_POST.get());
        this.dropSelf(ModBlocks.RED_WHITE_POST.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_POST.get());
        this.dropSelf(ModBlocks.RED_POST.get());
        this.dropSelf(ModBlocks.ROAD_EDGE_POST.get());
        this.dropSelf(ModBlocks.ORANGE_ROAD_EDGE_POST.get());

        this.dropSelf(ModBlocks.YELLOW_CHAIN.get());
        this.dropSelf(ModBlocks.BLACK_CHAIN.get());
        this.dropSelf(ModBlocks.WHITE_CHAIN.get());
        this.dropSelf(ModBlocks.RED_CHAIN.get());

        this.dropSelf(ModBlocks.LEFT_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.CAMPING_EU_SIGN.get());
        this.dropSelf(ModBlocks.PR_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_ROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_NARROWING_EU_SIGN.get());
        this.dropSelf(ModBlocks.CHURCH_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PARKING_EU_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_EU_SIGN.get());
        this.dropSelf(ModBlocks.NARROWING_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_CARS_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCK_PASSING_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.ONGOING_TRAFFIC_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.END_ALL_LIMITS_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIRECTION_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PASSING_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.CATTLE_EU_SIGN.get());
        this.dropSelf(ModBlocks.CAFE_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_VEHICLES_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCKS_EU_SIGN.get());
        this.dropSelf(ModBlocks.BUS_EU_SIGN.get());
        this.dropSelf(ModBlocks.DANGER_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_ENTER_EU_SIGN.get());
        this.dropSelf(ModBlocks.INTERSECTION_EU_SIGN.get());
        this.dropSelf(ModBlocks.EIGHTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.ASCEND_EU_SIGN.get());
        this.dropSelf(ModBlocks.CYCLES_EU_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_BAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PEDESTRIANS_EU_SIGN.get());
        this.dropSelf(ModBlocks.PASS_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.DESCEND_EU_SIGN.get());
        this.dropSelf(ModBlocks.FIRST_AID_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_BICYCLES_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_OVER_ONCOMING_TRAFFIC_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_THROUGH_ROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.CREEPER_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_ROAD_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DOUBLE_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_PATH_EU_SIGN.get());
        this.dropSelf(ModBlocks.JAMS_EU_SIGN.get());
        this.dropSelf(ModBlocks.KM_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PASSING_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCK_PASSING_EU_SIGN.get());
        this.dropSelf(ModBlocks.END_LINE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PASS_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_PARKING_ALONG_CARRIAGEWAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.SIXTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIANS_EU_SIGN.get());
        this.dropSelf(ModBlocks.CALMING_AREA_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_TURN_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.ONCOMING_TRAFFIC_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_HERE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.ONE_WAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.BUS_STOP_EU_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIAN_CROSSING_EU_SIGN.get());
        this.dropSelf(ModBlocks.INFO_EU_SIGN.get());
        this.dropSelf(ModBlocks.DISABLED_EU_SIGN.get());
        this.dropSelf(ModBlocks.TEN_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.CROSSBUCK_EU_SIGN.get());
        this.dropSelf(ModBlocks.THIRTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.HOTEL_EU_SIGN.get());
        this.dropSelf(ModBlocks.GATE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PETROL_STATION_EU_SIGN.get());
        this.dropSelf(ModBlocks.CHILDREN_EU_SIGN.get());
        this.dropSelf(ModBlocks.CROSSWALK_EU_SIGN.get());
        this.dropSelf(ModBlocks.END_CALMING_AREA_EU_SIGN.get());
        this.dropSelf(ModBlocks.GUIDE_EU_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_GARAGE_EU_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.HUNDRED_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_U_TURN_EU_SIGN.get());
        this.dropSelf(ModBlocks.HUNDRED_TWENTY_SPEED_EU_SIGN.get());
        this.dropSelf(ModBlocks.RAILROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.REPAIR_EU_SIGN.get());
        this.dropSelf(ModBlocks.RESTAURANT_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIRECTION_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DOUBLE_CURVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_HERE_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_NARROWING_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_ARROW_EU_SIGN.get());
        this.dropSelf(ModBlocks.ROADWORKS_EU_SIGN.get());
        this.dropSelf(ModBlocks.ROCKFALL_EU_SIGN.get());
        this.dropSelf(ModBlocks.ROUNDABOUT_EU_SIGN.get());
        this.dropSelf(ModBlocks.SIDEWALK_EU_SIGN.get());
        this.dropSelf(ModBlocks.SIGNAL_EU_SIGN.get());
        this.dropSelf(ModBlocks.SLIPPERINESS_EU_SIGN.get());
        this.dropSelf(ModBlocks.SNOW_EU_SIGN.get());
        this.dropSelf(ModBlocks.STOP_EU_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.TAXI_EU_SIGN.get());
        this.dropSelf(ModBlocks.TELEPHONE_EU_SIGN.get());
        this.dropSelf(ModBlocks.UNEVEN_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARN_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_ALT_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.WC_EU_SIGN.get());
        this.dropSelf(ModBlocks.WEIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.WET_EU_SIGN.get());
        this.dropSelf(ModBlocks.YIELD_RIGHT_OF_WAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.NATURE_RESERVE_EU_SIGN.get());
        this.dropSelf(ModBlocks.MOTORWAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.MOTORWAY_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.WATER_PROTECTION_AREA_EU_SIGN.get());

        this.dropSelf(ModBlocks.REPAIR_US_SIGN.get());
        this.dropSelf(ModBlocks.HILL_US_SIGN.get());
        this.dropSelf(ModBlocks.GUIDE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ADDED_LINE_US_SIGN.get());
        this.dropSelf(ModBlocks.INFO_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ENTERING_ROADWAY_MERGE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.DOUBLE_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.HOTEL_US_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIANS_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_BICYCLE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_LANE_ENDS_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIAGONAL_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.HANDICAPPED_ACCESSIBLE_US_SIGN.get());
        this.dropSelf(ModBlocks.RESTAURANT_US_SIGN.get());
        this.dropSelf(ModBlocks.HAIRPIN_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.AIRPORT_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIRECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.RAILROAD_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ENTERING_ROADWAY_MERGE_US_SIGN.get());
        this.dropSelf(ModBlocks.DRINKING_WATER_US_SIGN.get());
        this.dropSelf(ModBlocks.CRAFT_CITY_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_LEFT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIAGONAL_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.BATHROOMS_US_SIGN.get());
        this.dropSelf(ModBlocks.LITTER_BARREL_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_TRUCKS_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_TURN_ONLY_US_SIGN.get());
        this.dropSelf(ModBlocks.FORTYFIVE_ADVISORY_SPEED_US_SIGN.get());
        this.dropSelf(ModBlocks.LIGHT_RAIL_TRANSIT_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.CRAFT_CITY_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.HOSPITAL_US_SIGN.get());
        this.dropSelf(ModBlocks.GAS_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.CATTLE_US_SIGN.get());
        this.dropSelf(ModBlocks.HANDICAPED_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.PICNIC_AREA_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_U_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIAGONAL_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ADDED_LINE_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_LANE_ENDS_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_SIDE_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.PLAYGROUND_AHEAD_US_SIGN.get());
        this.dropSelf(ModBlocks.DIESEL_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.THIRTYFIVE_ADVISORY_SPEED_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIAGONAL_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.CREEPER_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIAGONAL_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.LOUNDRY_FACILITY_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_PARKING_US_SIGN.get());
        this.dropSelf(ModBlocks.TWENTYFIVE_ADVISORY_SPEED_US_SIGN.get());
        this.dropSelf(ModBlocks.DOUBLE_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.CAMPING_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.CIRCULAR_INTERSECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_MERGING_TRAFFIC_US_SIGN.get());
        this.dropSelf(ModBlocks.DIVIDED_HIGHWAY_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_PEDESTRIANS_US_SIGN.get());
        this.dropSelf(ModBlocks.CROSSBUCK_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.ELECTRIC_STATION_US_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_REVERSE_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_ARROW_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.MEDICAL_SERVICE_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIRECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_RIGHT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.CROSS_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.DOUBLE_ARROW_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIAGONAL_ARROW_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_MERGING_TRAFFIC_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_REVERSE_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_SIDE_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_ONLY_US_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_US_SIGN.get());
        this.dropSelf(ModBlocks.ROAD_NARROWS_US_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_ANGLE_LEFT_US_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_ANGLE_RIGHT_US_SIGN.get());
        this.dropSelf(ModBlocks.SIGNAL_US_SIGN.get());
        this.dropSelf(ModBlocks.SLIPPERY_US_SIGN.get());
        this.dropSelf(ModBlocks.STRAIGHT_AHEAD_ONLY_US_SIGN.get());
        this.dropSelf(ModBlocks.SWIMMING_AREA_US_SIGN.get());
        this.dropSelf(ModBlocks.T_INTERSECTION_US_SIGN.get());
        this.dropSelf(ModBlocks.TELEPHONE_US_SIGN.get());
        this.dropSelf(ModBlocks.TRUCK_CROSSING_US_SIGN.get());
        this.dropSelf(ModBlocks.TRUCK_ROLLOVER_WARNING_US_SIGN.get());
        this.dropSelf(ModBlocks.TWO_WAY_TRAFFIC_US_SIGN.get());
        this.dropSelf(ModBlocks.VERY_SHARP_CURVE_US_SIGN.get());
        this.dropSelf(ModBlocks.WINTER_RECREATION_AREA_US_SIGN.get());
        this.dropSelf(ModBlocks.WINDING_ROAD_US_SIGN.get());
        this.dropSelf(ModBlocks.WORKERS_US_SIGN.get());
        this.dropSelf(ModBlocks.Y_INTERSECTION_US_SIGN.get());

        this.dropSelf(ModBlocks.ONCOMING_TRAFFIC_CN_SIGN.get());
        this.dropSelf(ModBlocks.INTERSECTION_CN_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_LEFT_OR_RIGHT_CN_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIAN_CROSSING_CN_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_BAY_CN_SIGN.get());
        this.dropSelf(ModBlocks.CATTLE_CN_SIGN.get());
        this.dropSelf(ModBlocks.NARROWING_CN_SIGN.get());
        this.dropSelf(ModBlocks.DESCEND_CN_SIGN.get());
        this.dropSelf(ModBlocks.CHILDREN_CN_SIGN.get());
        this.dropSelf(ModBlocks.FIFTY_ADVISORY_SPEED_CN_SIGN.get());
        this.dropSelf(ModBlocks.JAMS_CN_SIGN.get());
        this.dropSelf(ModBlocks.DANGER_CN_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DOUBLE_CURVE_CN_SIGN.get());
        this.dropSelf(ModBlocks.RAILROAD_CN_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_LEFT_CN_SIGN.get());
        this.dropSelf(ModBlocks.CREEPER_CN_SIGN.get());
        this.dropSelf(ModBlocks.ASCEND_CN_SIGN.get());
        this.dropSelf(ModBlocks.GAS_STATION_CN_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_CN_SIGN.get());
        this.dropSelf(ModBlocks.BUMP_CN_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DIRECTION_CN_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_NARROWING_CN_SIGN.get());
        this.dropSelf(ModBlocks.INFO_CN_SIGN.get());
        this.dropSelf(ModBlocks.CYCLES_CN_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_CN_SIGN.get());
        this.dropSelf(ModBlocks.CAMPING_CN_SIGN.get());
        this.dropSelf(ModBlocks.ROUNDABOUT_CN_SIGN.get());
        this.dropSelf(ModBlocks.SHORE_CN_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_CN_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_CURVE_CN_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_NARROWING_CN_SIGN.get());
        this.dropSelf(ModBlocks.NATURE_RESERVE_AREA_CN_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_MERGING_TRAFFIC_CN_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_END_CN_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_DOUBLE_CURVE_CN_SIGN.get());
        this.dropSelf(ModBlocks.GATE_CN_SIGN.get());
        this.dropSelf(ModBlocks.ROCKFALL_CN_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_GARAGE_CN_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_RIGHT_CN_SIGN.get());
        this.dropSelf(ModBlocks.THIRTY_ADVISORY_SPEED_CN_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_DIRECTION_CN_SIGN.get());
        this.dropSelf(ModBlocks.NARROW_BRIDGE_CN_SIGN.get());
        this.dropSelf(ModBlocks.FORTY_ADVISORY_SPEED_CN_SIGN.get());
        this.dropSelf(ModBlocks.ONE_WAY_CN_SIGN.get());
        this.dropSelf(ModBlocks.ROADWORKS_CN_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_MERGING_TRAFFIC_CN_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_CURVE_CN_SIGN.get());
        this.dropSelf(ModBlocks.GUIDE_CN_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_ANGLE_LEFT_CN_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_ANGLE_RIGHT_CN_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_LEFT_CN_SIGN.get());
        this.dropSelf(ModBlocks.SIDE_ROAD_AT_RIGHT_CN_SIGN.get());
        this.dropSelf(ModBlocks.SIGNAL_CN_SIGN.get());
        this.dropSelf(ModBlocks.SLIPPERINESS_CN_SIGN.get());
        this.dropSelf(ModBlocks.SLOW_CN_SIGN.get());
        this.dropSelf(ModBlocks.SNOW_CN_SIGN.get());
        this.dropSelf(ModBlocks.STOP_CN_SIGN.get());
        this.dropSelf(ModBlocks.T_INTERSECTION_CN_SIGN.get());
        this.dropSelf(ModBlocks.TELEPHONE_CN_SIGN.get());
        this.dropSelf(ModBlocks.UNEVEN_ROAD_CN_SIGN.get());

        this.dropSelf(ModBlocks.ROUND_SIGN.get());
        this.dropSelf(ModBlocks.TRIANGLE_SIGN.get());
        this.dropSelf(ModBlocks.RECTANGLE_SIGN.get());
        this.dropSelf(ModBlocks.SQUARE_SIGN.get());
        this.dropSelf(ModBlocks.CROSS_SIGN.get());
        this.dropSelf(ModBlocks.UPSIDE_DOWN_TRIANGLE_SIGN.get());
        this.dropSelf(ModBlocks.RHOMBUS_SIGN.get());
        this.dropSelf(ModBlocks.OCTAGON_SIGN.get());
        this.dropSelf(ModBlocks.BAKE_SIGN.get());

        this.add(ModBlocks.DRAIN_COVER.get(), block -> createSlabItemTable(ModBlocks.DRAIN_COVER.get()));
        this.add(ModBlocks.DRAIN_COVER_GRID.get(), block -> createSlabItemTable(ModBlocks.DRAIN_COVER_GRID.get()));

        this.dropSelf(ModBlocks.IRON_FENCE.get());
        this.dropSelf(ModBlocks.TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.RED_WHITE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.DOUBLE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.DOUBLE_YELLOW_BLACK_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.DOUBLE_RED_WHITE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.RED_WHITE_TRAFFIC_BARRIER.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_TRAFFIC_BARRIER.get());

        this.dropSelf(ModBlocks.BLACK_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.WHITE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.ORANGE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.MAGENTA_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.YELLOW_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.LIME_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.PINK_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.GRAY_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.CYAN_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.PURPLE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.BLUE_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.BROWN_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.GREEN_CONCRETE_WALL.get());
        this.dropSelf(ModBlocks.RED_CONCRETE_WALL.get());

        this.dropSelf(ModBlocks.BLOCK_PAINTER.get());

        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_BICYCLE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_HANDICAPPED.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_PEDESTRIAN.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_WHITE_TRIANGLE.get());
        this.add(ModBlocks.ASPHALT_WITH_WHITE_BICYCLE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_BICYCLE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_DIAGONAL_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_HANDICAPPED_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_HANDICAPPED_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_PEDESTRIAN_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_PEDESTRIAN_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_WHITE_TRIANGLE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_WHITE_TRIANGLE_SLAB.get()));
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_BICYCLE.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LEFT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_RIGHT_ARROW.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_HANDICAPPED.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_PEDESTRIAN.get());
        this.dropSelf(ModBlocks.ASPHALT_WITH_YELLOW_TRIANGLE.get());
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_BICYCLE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_BICYCLE_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LEFT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_LEFT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_RIGHT_ARROW_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_DIAGONAL_RIGHT_ARROW_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_HANDICAPPED_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_HANDICAPPED_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_PEDESTRIAN_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_PEDESTRIAN_SLAB.get()));
        this.add(ModBlocks.ASPHALT_WITH_YELLOW_TRIANGLE_SLAB.get(), block -> createSlabItemTable(ModBlocks.ASPHALT_WITH_YELLOW_TRIANGLE_SLAB.get()));

        this.dropSelf(ModBlocks.RED_WHITE_BARRIER_TAPE.get());
        this.dropSelf(ModBlocks.YELLOW_BLACK_BARRIER_TAPE.get());

        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_LANE_OPEN.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_LANE_CLOSED.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_LANE_CHANGE_LEFT.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_LANE_CHANGE_RIGHT.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_SIXTY_SPEED_LIMIT.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_EIGHTY_SPEED_LIMIT.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_HUNDRED_SPEED_LIMIT.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_HUNDRED_TWENTY_SPEED_LIMIT.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_END_ALL_LIMITS.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_CREEPER.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_DANGER.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_JAMS.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_NO_PASSING.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_NO_TRUCK_PASSING.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_ROADWORKS.get());
        this.dropSelf(ModBlocks.VARIABLE_TRAFFIC_SIGN_SLIPPERINESS.get());

        this.dropSelf(ModBlocks.EXIT_CLOSED_US_SIGN.get());
        this.dropSelf(ModBlocks.NO_HAZARDOUS_CARGO_EU_SIGN.get());
        this.dropSelf(ModBlocks.M_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.AHEAD_YELLOW_US_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_PATH_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_HIGHWAY_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.TEN_MINIMUM_SPEED_SIGN_EU.get());
        this.dropSelf(ModBlocks.HIGHWAY_COUNTDOWN_MARKER_200_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_PATH_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_ROUTE_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.FEDERAL_HIGHWAY_COUNTDOWN_MARKER_100_EU_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_COUNTDOWN_MARKER_300_EU_SIGN.get());
        this.dropSelf(ModBlocks.BRIDLE_PATH_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_LEFT_US_SIGN.get());
        this.dropSelf(ModBlocks.FEDERAL_HIGHWAY_COUNTDOWN_MARKER_200_EU_SIGN.get());
        this.dropSelf(ModBlocks.DETOUR_RIGHT_US_SIGN.get());
        this.dropSelf(ModBlocks.AHEAD_GREEN_US_SIGN.get());
        this.dropSelf(ModBlocks.MOVABLE_BRIDGE_EU_SIGN.get());
        this.dropSelf(ModBlocks.HIGHWAY_COUNTDOWN_MARKER_100_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_PATH_US_SIGN.get());
        this.dropSelf(ModBlocks.THIRTY_MINIMUM_SPEED_SIGN_EU.get());
        this.dropSelf(ModBlocks.CHARGING_STATION_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_ROUTE_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.LOOSE_GRAVEL_EU_SIGN.get());
        this.dropSelf(ModBlocks.FEDERAL_HIGHWAY_COUNTDOWN_MARKER_300_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_HIGHWAY_EU_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_AREA_END_EU_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_PATH_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.NO_MONSTER_EU_SIGN.get());
        this.dropSelf(ModBlocks.AHEAD_ORANGE_US_SIGN.get());
        this.dropSelf(ModBlocks.BICYCLE_ROUTE_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.LEFT_PRIORITY_ROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.PARKING_AREA_START_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_ROAD_FROM_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.PRIORITY_ROAD_FROM_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.RAILWAY_COUNTDOWN_MARKER_80_EU_SIGN.get());
        this.dropSelf(ModBlocks.RAILWAY_COUNTDOWN_MARKER_160_EU_SIGN.get());
        this.dropSelf(ModBlocks.RAILWAY_COUNTDOWN_MARKER_240_EU_SIGN.get());
        this.dropSelf(ModBlocks.RIGHT_PRIORITY_ROAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.SHORE_EU_SIGN.get());
        this.dropSelf(ModBlocks.TREE_OVERHANG_EU_SIGN.get());
        this.dropSelf(ModBlocks.TRUCK_ROUTE_AHEAD_EU_SIGN.get());
        this.dropSelf(ModBlocks.TRUCK_ROUTE_RIGHT_EU_SIGN.get());
        this.dropSelf(ModBlocks.TRUCK_ROUTE_LEFT_EU_SIGN.get());
        this.dropSelf(ModBlocks.WARN_US_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_ALT_US_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_LEFT_US_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_BEACON_RIGHT_US_SIGN.get());

        this.dropSelf(ModBlocks.ENTERING_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.HEAVY_LOAD_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.LASER_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.GLOVES_MANDATORY_SIGN.get());
        this.dropSelf(ModBlocks.MANDATORY_SIGN.get());
        this.dropSelf(ModBlocks.FIRE_EXTINGUISHER_SIGN.get());
        this.dropSelf(ModBlocks.DRINKING_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.BOOTS_MANDATORY_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_EXIT_LEFT_SIGN.get());
        this.dropSelf(ModBlocks.FIRE_TELEPHONE_SIGN.get());
        this.dropSelf(ModBlocks.HELMET_MANDATORY_SIGN.get());
        this.dropSelf(ModBlocks.HOT_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.EXPLOSION_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_EXIT_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_TELEFONE_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_EXIT_DOWNWARDS_SIGN.get());
        this.dropSelf(ModBlocks.MONSTER_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.MAGNETIC_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.FIRE_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.BIOHAZARD_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.ASSEMBLY_POINT_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_EXIT_RIGHT_SIGN.get());
        this.dropSelf(ModBlocks.EATING_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.EMERGENCY_EXIT_AHEAD_SIGN.get());
        this.dropSelf(ModBlocks.ARMOR_MANDATORY_SIGN.get());
        this.dropSelf(ModBlocks.EXIT_SIGN.get());
        this.dropSelf(ModBlocks.GAS_CYLINDER_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.FIRST_AID_SIGN.get());
        this.dropSelf(ModBlocks.FIRE_ALARM_SIGN.get());
        this.dropSelf(ModBlocks.PEDESTRIANS_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.PHONES_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.PROHIBITION_SIGN.get());
        this.dropSelf(ModBlocks.RADIATION_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.SMOKING_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.TOXIC_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.UNAUTHORISED_PROHIBITED_SIGN.get());
        this.dropSelf(ModBlocks.VOLTAGE_WARNING_SIGN.get());
        this.dropSelf(ModBlocks.WARNING_SIGN.get());

        this.dropSelf(ModBlocks.SIGN_0.get());
        this.dropSelf(ModBlocks.SIGN_1.get());
        this.dropSelf(ModBlocks.SIGN_2.get());
        this.dropSelf(ModBlocks.SIGN_3.get());
        this.dropSelf(ModBlocks.SIGN_4.get());
        this.dropSelf(ModBlocks.SIGN_5.get());
        this.dropSelf(ModBlocks.SIGN_6.get());
        this.dropSelf(ModBlocks.SIGN_7.get());
        this.dropSelf(ModBlocks.SIGN_8.get());
        this.dropSelf(ModBlocks.SIGN_9.get());
        this.dropSelf(ModBlocks.A_SIGN.get());
        this.dropSelf(ModBlocks.B_SIGN.get());
        this.dropSelf(ModBlocks.C_SIGN.get());
        this.dropSelf(ModBlocks.D_SIGN.get());
        this.dropSelf(ModBlocks.E_SIGN.get());
        this.dropSelf(ModBlocks.F_SIGN.get());
        this.dropSelf(ModBlocks.G_SIGN.get());
        this.dropSelf(ModBlocks.H_SIGN.get());
        this.dropSelf(ModBlocks.I_SIGN.get());
        this.dropSelf(ModBlocks.J_SIGN.get());
        this.dropSelf(ModBlocks.K_SIGN.get());
        this.dropSelf(ModBlocks.L_SIGN.get());
        this.dropSelf(ModBlocks.M_SIGN.get());
        this.dropSelf(ModBlocks.N_SIGN.get());
        this.dropSelf(ModBlocks.O_SIGN.get());
        this.dropSelf(ModBlocks.P_SIGN.get());
        this.dropSelf(ModBlocks.Q_SIGN.get());
        this.dropSelf(ModBlocks.R_SIGN.get());
        this.dropSelf(ModBlocks.S_SIGN.get());
        this.dropSelf(ModBlocks.T_SIGN.get());
        this.dropSelf(ModBlocks.U_SIGN.get());
        this.dropSelf(ModBlocks.V_SIGN.get());
        this.dropSelf(ModBlocks.W_SIGN.get());
        this.dropSelf(ModBlocks.X_SIGN.get());
        this.dropSelf(ModBlocks.Y_SIGN.get());
        this.dropSelf(ModBlocks.Z_SIGN.get());
        this.dropSelf(ModBlocks.EXCLAMATION_SIGN.get());
        this.dropSelf(ModBlocks.QUESTION_SIGN.get());

        this.dropSelf(ModBlocks.BICYCLE_DOUBLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.BICYCLE_TRIPPLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.DANGER_SIGNAL_LIGHT.get());
        this.dropSelf(ModBlocks.DOUBLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.LEFT_TURN_DOUBLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.LEFT_TURN_TRIPPLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.PEDESTRIAN_DOUBLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.PEDESTRIAN_SIGNAL_LIGHT.get());
        this.dropSelf(ModBlocks.PEDESTRIAN_TRIPPLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_DOUBLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.RIGHT_TURN_TRIPPLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.SIGNAL_LIGHT.get());
        this.dropSelf(ModBlocks.STRAIGHT_DOUBLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.STRAIGHT_TRIPPLE_TRAFFIC_LIGHT.get());
        this.dropSelf(ModBlocks.TRAIN_SIGNAL_LIGHT.get());
        this.dropSelf(ModBlocks.TRIPPLE_TRAFFIC_LIGHT.get());

        this.dropSelf(ModBlocks.BLACK_LAMP.get());
        this.dropSelf(ModBlocks.WHITE_LAMP.get());
        this.dropSelf(ModBlocks.ORANGE_LAMP.get());
        this.dropSelf(ModBlocks.MAGENTA_LAMP.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_LAMP.get());
        this.dropSelf(ModBlocks.YELLOW_LAMP.get());
        this.dropSelf(ModBlocks.LIME_LAMP.get());
        this.dropSelf(ModBlocks.PINK_LAMP.get());
        this.dropSelf(ModBlocks.GRAY_LAMP.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_LAMP.get());
        this.dropSelf(ModBlocks.CYAN_LAMP.get());
        this.dropSelf(ModBlocks.PURPLE_LAMP.get());
        this.dropSelf(ModBlocks.BLUE_LAMP.get());
        this.dropSelf(ModBlocks.BROWN_LAMP.get());
        this.dropSelf(ModBlocks.GREEN_LAMP.get());
        this.dropSelf(ModBlocks.RED_LAMP.get());

        this.dropSelf(ModBlocks.BLACK_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.WHITE_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.ORANGE_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.MAGENTA_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.YELLOW_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.LIME_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.PINK_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.GRAY_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.CYAN_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.PURPLE_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.BLUE_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.BROWN_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.GREEN_NEON_LIGHT.get());
        this.dropSelf(ModBlocks.RED_NEON_LIGHT.get());

        this.dropSelf(ModBlocks.CRACKED_WHITE_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_LIGHT_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_BLACK_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_BROWN_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_RED_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_ORANGE_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_YELLOW_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_LIME_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_GREEN_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_CYAN_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_LIGHT_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_PURPLE_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_MAGENTA_CONCRETE.get());
        this.dropSelf(ModBlocks.CRACKED_PINK_CONCRETE.get());

        this.dropSelf(ModBlocks.MOSSY_WHITE_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_LIGHT_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_BLACK_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_BROWN_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_RED_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_ORANGE_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_YELLOW_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_LIME_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_GREEN_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_CYAN_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_LIGHT_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_PURPLE_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_MAGENTA_CONCRETE.get());
        this.dropSelf(ModBlocks.MOSSY_PINK_CONCRETE.get());

        this.add(ModBlocks.INFESTED_BLACK_CONCRETE.get(), block -> createSilkTouchDispatchTable(block, LootItem.lootTableItem(Items.BLACK_CONCRETE)));
        this.add(ModBlocks.INFESTED_WHITE_CONCRETE.get(), block -> createSilkTouchDispatchTable(block, LootItem.lootTableItem(Items.WHITE_CONCRETE)));
        this.add(ModBlocks.INFESTED_GRAY_CONCRETE.get(), block -> createSilkTouchDispatchTable(block, LootItem.lootTableItem(Items.GRAY_CONCRETE)));
        this.add(ModBlocks.INFESTED_LIGHT_GRAY_CONCRETE.get(), block -> createSilkTouchDispatchTable(block, LootItem.lootTableItem(Items.LIGHT_GRAY_CONCRETE)));

        this.dropSelf(ModBlocks.CHISELED_WHITE_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_LIGHT_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_BLACK_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_BROWN_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_RED_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_ORANGE_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_YELLOW_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_LIME_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_GREEN_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_CYAN_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_LIGHT_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_PURPLE_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_MAGENTA_CONCRETE.get());
        this.dropSelf(ModBlocks.CHISELED_PINK_CONCRETE.get());

        this.dropSelf(ModBlocks.POLISHED_WHITE_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_LIGHT_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_GRAY_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_BLACK_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_BROWN_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_RED_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_ORANGE_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_YELLOW_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_LIME_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_GREEN_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_CYAN_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_LIGHT_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_BLUE_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_PURPLE_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_MAGENTA_CONCRETE.get());
        this.dropSelf(ModBlocks.POLISHED_PINK_CONCRETE.get());

        this.dropSelf(ModBlocks.WHITE_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.GRAY_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.BLACK_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.BROWN_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.RED_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.ORANGE_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.YELLOW_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.LIME_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.GREEN_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.CYAN_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.BLUE_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.PURPLE_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.MAGENTA_CONCRETE_PILLAR.get());
        this.dropSelf(ModBlocks.PINK_CONCRETE_PILLAR.get());

        this.dropSelf(ModBlocks.WHITE_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.LIGHT_GRAY_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.GRAY_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.BLACK_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.BROWN_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.RED_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.ORANGE_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.YELLOW_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.LIME_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.GREEN_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.CYAN_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.LIGHT_BLUE_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.BLUE_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.PURPLE_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.MAGENTA_CONCRETE_STAIRS.get());
        this.dropSelf(ModBlocks.PINK_CONCRETE_STAIRS.get());

        this.dropSelf(ModBlocks.STREET_LANTERN.get());
        this.dropSelf(ModBlocks.MODERN_STREET_LANTERN.get());
        this.add(ModBlocks.STREET_LANTERN_PANEL.get(), block -> createSlabItemTable(ModBlocks.STREET_LANTERN_PANEL.get()));
    }


    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries() // Get all registered entries
                .stream() // Stream the wrapped objects
                .map(Holder::value) // Get the object if available
                .toList(); // Create the iterable
    }
}
